### ISSUE TITLE
Ensure that there is a timestamp added to the message for each step in the crawling process.

### ISSUE THREAD

**Issue by peoplespete** [seattleagainstslavery/crawlers#120]
We currently have:
```
        "site-map": "2019-12-14T23:31:59",
        "ad-listing-crawled": "2020-06-03T08:03:40",
        "ad-crawled": "2020-06-03T10:14:19",
        "ad-parsed": "2020-07-15T21:44:52"
```

in the metadata section of the Cosmos records.
We should make sure that at each stage we add a timestamp.
The one that caused us to think we should do this was during troubleshooting when we did not have a timestamp for when something was "process"ed.

**Comment by lizrush** [comment]
Handled in Ads repo
