### ISSUE TITLE
http://vipgirlfriend.com/ forwards to https://vipgirlfriend.xxx/about

### ISSUE THREAD

**Issue by peoplespete** [seattleagainstslavery/crawlers#153]
We used to have a crawler for vipgirlfriend but it was turned off. We could resurrect it (assuming it still works) or create a new one for this site.

**Comment by peoplespete** [comment]
https://listings.vipgirlfriend.xxx/
That is the endpoint where the listings are.

**Comment by lizrush** [comment]
moved to clubhouse
